web: uvicorn app.main:app --host 0.0.0.0 --port $PORT
worker: python -m celery -A app.core.celery_tasks.celery_app worker --loglevel=info --concurrency=2
beat: python -m celery -A app.core.celery_tasks.celery_app beat --loglevel=info
